# Generated by Django 4.2.16 on 2024-11-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('referencia', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=100)),
                ('remitente', models.CharField(max_length=30)),
                ('cargoRemitente', models.CharField(max_length=30)),
                ('observacion', models.CharField(max_length=255)),
                ('fojas', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('destinatarios', models.ManyToManyField(related_name='documentos_recibidos', to='registro.destinatario')),
            ],
        ),
    ]
